apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-mock-oidc.fullname" . }}
  labels:
    {{- include "dev-mock-oidc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dev-mock-oidc.selectorLabels" . | nindent 4 }}
