apiVersion: v2
name: sensitive-data-archive
description: A Helm chart for the Sensitive Data Archive (SDA)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: sda-db
    version: ^0
    condition: sda-db.deploy

  - name: sda-mq
    version: ^0
    condition: sda-mq.deploy

  - name: sda-orch
    version: ^0
    condition: sda-orch.deploy

  - name: sda-svc
    version: ^0
    condition: sda-svc.deploy

  - name: dev-s3
    version: ^0
    condition: develop.s3

  - name: dev-mock-oidc
    version: ^0
    condition: develop.oidc
