apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev-s3.fullname" . }}
  labels:
    {{- include "dev-s3.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dev-s3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dev-s3.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "dev-s3.fullname" . }}-pvc
      - name: certs
        secret:
          secretName: {{ template "dev-s3.fullname" . }}-dev-s3-certs
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  mkdir -p /root/.minio/certs/CAs;
                  ln -s /certs/tls.crt /root/.minio/certs/public.crt;
                  ln -s /certs/tls.key /root/.minio/certs/private.key;
                  ln -s /certs/ca.crt /root/.minio/certs/CAs/public.crt;
        volumeMounts:
          - name: data
            mountPath: /data
          - name: certs
            mountPath: /certs
        args:
        - server
        - /data
        - --console-address
        - :9001
        env:
        # MinIO access key and secret key
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "dev-s3.fullname" . }}
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "dev-s3.fullname" . }}
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_SERVER_URL
          value: https://127.0.0.1:9000
        ports:
          - name: s3
            containerPort: 9000
            protocol: TCP
          - name: admin
            containerPort: 9001
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        # Readiness probe detects situations when MinIO server instance
        # is not ready to accept traffic. Kubernetes doesn't forward
        # traffic to the pod while readiness checks fail.
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /minio/health/ready
            port: s3
          initialDelaySeconds: 30
          periodSeconds: 20
        # Liveness probe detects situations where MinIO server instance
        # is not working properly and needs restart. Kubernetes automatically
        # restarts the pods if liveness checks fail.
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /minio/health/live
            port: s3
          initialDelaySeconds: 30
          periodSeconds: 20
