apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dev-s3.fullname" . }}-pvc
  labels:
    {{- include "dev-s3.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize }}
