apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-mock-oidc.fullname" . }}-oidc
  labels:
    {{- include "dev-mock-oidc.labels" . | nindent 4 }}
data:
  port: "9090"
  host: {{ template "sda.mockOidcHost" . }}
  client_id: XC56EL11xx
  client_secret: wHPVQaYXmdDHg
  client_redirect_uri: http://kubernetes.docker.internal/elixir/login
  auth_route: /auth
  introspection_route: /token/introspection
  jwks_route: /jwks
  revocation_route: /token/revocation
  token_route: /token
  userinfo_route: /userinfo
