{{- if or .Values.global.tls.clusterIssuer .Values.global.tls.issuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "dev-s3.fullname" . }}-dev-s3-certs
spec:
  # Secret names are always required.
  secretName: {{ template "dev-s3.fullname" . }}-dev-s3-certs

  duration: 2160h # 90d

  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ include "dev-s3.fullname" . }}
    - {{ include "dev-s3.fullname" . }}.{{ .Release.Namespace }}.svc
  ipAddresses:
    - 127.0.0.1
  # Issuer references are always required.
  issuerRef:
    name: {{ .Values.global.tls.issuer }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
{{- end -}}
