apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-s3.fullname" . }}
  labels:
    {{- include "dev-s3.labels" . | nindent 4 }}
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123
