apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-s3.fullname" . }}
  labels:
    {{- include "dev-s3.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    {{- include "dev-s3.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-s3.fullname" . }}-admin
  labels:
    {{- include "dev-s3.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
      nodePort: 30091
  selector:
    {{- include "dev-s3.selectorLabels" . | nindent 4 }}
