{{- if not .Values.global.vaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.auth.jwtSecret }}
type: Opaque
data:
  {{ .Values.global.auth.jwtKey }}: {{ .Values.global.auth.jwtPrivateKey | b64enc }}
  {{ .Values.global.auth.jwtPub }}: {{ .Values.global.auth.jwtPublicKey | b64enc }}
{{- end }}
